apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: postgresql:latest
    creationTimestamp: null
    labels:
      app: postgresql
    name: postgresql:latest
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: postgresql:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql
    name: postgresql
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: postgresql:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: samples/postgresql
      git:
        uri: https://github.com/teiid/teiid-operator.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: postgresql:9.5
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: hf9uS-dRXYk9-WzPUoXy
      type: GitHub
    - generic:
        secret: NBZrwk_dhK4NlJgNmsJ-
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql
    name: postgresql
  spec:
    replicas: 1
    selector:
      app: postgresql
      deploymentconfig: postgresql
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: postgresql
          deploymentconfig: postgresql
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: sampledb
          - name: POSTGRESQL_PASSWORD
            value: mypassword
          - name: POSTGRESQL_USER
            value: user
          image: postgresql:latest
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          resources: {}
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-volume-1
        volumes:
        - emptyDir: {}
          name: postgresql-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql
    name: postgresql
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql
      deploymentconfig: postgresql
  status:
    loadBalancer: {}
kind: List
metadata: {}
